# Generated by Django 5.1.2 on 2025-07-27 03:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('complaint_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('problem', models.CharField(max_length=255)),
                ('problem_description', models.TextField()),
                ('ict_response', models.TextField(blank=True, null=True)),
                ('complain_satisfy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('unsatisfied_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('signed_by_staff', models.CharField(max_length=255)),
                ('signed_by_hod_ict', models.CharField(max_length=255)),
                ('signed_by_head_section', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
